apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: reflector
    releaseName: reflector
    version: 7.0.190
    repo: https://emberstack.github.io/helm-charts
    valuesFile: values-reflector.yaml
    namespace: base-utils

  - name: reloader
    releaseName: reloader
    version: 1.0.67
    repo: https://stakater.github.io/stakater-charts
    valuesFile: values-reloader.yaml
    namespace: base-utils

  - name: external-secrets
    releaseName: external-secrets
    version: 0.17.0
    repo: https://charts.external-secrets.io
    valuesFile: values-external-secrets.yaml
    namespace: external-secrets
    includeCRDs: true
