apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tazama

resources:
  - namespace.yaml
  - pgadmin-servers-configmap.yaml
  - utils-workloads.yaml

images:
  - name: tazamaorg/nats-utilities
    newTag: rc
