apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tazama

resources:
  - namespace.yaml
  - observability-workloads.yaml

images:
  - name: tazamaorg/event-sidecar
    newTag: rc
  - name: tazamaorg/lumberjack
    newTag: rc
